// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

#nullable disable

namespace WebApi.Migrations.SqlServerMigrations
{
    [DbContext(typeof(SqliteDataContext))]
    [Migration("20240422214157_ShediMigration")]
    partial class ShediMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Admission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chambre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePEC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Désignation")
                        .HasColumnType("TEXT");

                    b.Property<int>("Identifiant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricule")
                        .HasColumnType("TEXT");

                    b.Property<int>("MédecinCorrespondantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MédecinTraitantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nationnalité")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumCIN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumPEC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prenom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Période")
                        .HasColumnType("TEXT");

                    b.Property<string>("SJour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Société")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("dossierPatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MédecinCorrespondantId");

                    b.HasIndex("MédecinTraitantId");

                    b.HasIndex("dossierPatientId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("DossierPatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdrChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdresseLocale")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostale")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatCIN")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatNai")
                        .HasColumnType("TEXT");

                    b.Property<string>("Délégation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Empreinte")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gouvernorat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricule")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationnalité")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomCli")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumCIN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientPEC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pays")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom2")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrenomPere")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prestataire")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tel2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Traite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DossierPatients");
                });

            modelBuilder.Entity("EmploiDuTemps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEmploi")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HDebutApMidi")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HDébutMatinée")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HDébutSoir")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HFinApMidi")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HFinMatinée")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HFinSoir")
                        .HasColumnType("TEXT");

                    b.Property<int>("KinéId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KinéId");

                    b.ToTable("EmploiDuTemps");
                });

            modelBuilder.Entity("RendezVous", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Désignation")
                        .HasColumnType("TEXT");

                    b.Property<int>("MédecinCorrespondantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MédecinTraitantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dateRDV")
                        .HasColumnType("TEXT");

                    b.Property<int>("dossierPatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("heureRDV")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MédecinCorrespondantId");

                    b.HasIndex("MédecinTraitantId");

                    b.HasIndex("dossierPatientId");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("WebApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CIN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Admission", b =>
                {
                    b.HasOne("WebApi.Entities.User", "MédecinCorrespondant")
                        .WithMany()
                        .HasForeignKey("MédecinCorrespondantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.User", "MédecinTraitant")
                        .WithMany()
                        .HasForeignKey("MédecinTraitantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DossierPatient", "dossierPatient")
                        .WithMany()
                        .HasForeignKey("dossierPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MédecinCorrespondant");

                    b.Navigation("MédecinTraitant");

                    b.Navigation("dossierPatient");
                });

            modelBuilder.Entity("EmploiDuTemps", b =>
                {
                    b.HasOne("WebApi.Entities.User", "Kiné")
                        .WithMany()
                        .HasForeignKey("KinéId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kiné");
                });

            modelBuilder.Entity("RendezVous", b =>
                {
                    b.HasOne("WebApi.Entities.User", "MédecinCorrespondant")
                        .WithMany()
                        .HasForeignKey("MédecinCorrespondantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.User", "MédecinTraitant")
                        .WithMany()
                        .HasForeignKey("MédecinTraitantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DossierPatient", "dossierPatient")
                        .WithMany()
                        .HasForeignKey("dossierPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MédecinCorrespondant");

                    b.Navigation("MédecinTraitant");

                    b.Navigation("dossierPatient");
                });
#pragma warning restore 612, 618
        }
    }
}
